### PR TITLE
Kyle local

### PR DESCRIPTION
**Pull request by kdettman**
Added csv files of state-wide ASOS average daily temperature data, processed through a rolling mean with a window of 3 days and a gaussian of std = 7 days.

### CODE REVIEW

**Review by emapple — CHANGES_REQUESTED** [review]
Please remove the checkpoint files and ASOS_station file if it's not needed, the pycache files, and the .py files if they're not needed.

I suspect the reason these are being added is that you have not merged in the master branch since it has been updated.

To do so, you can do
```
git checkout master
git pull
git checkout kyle_local
git merge master
```

Then please make sure the only files you are adding are the *csv files, nless the ASOS_stations.txt file is necessary.

**Comment by emapple** [comment]
@kdettman Another question -- do we want the Gaussian-convolved data, or the raw daily data? I would think we'd want the raw data, since we can always convolve later; that's very quick.

**Comment by kdettman** [comment]
I'll keep the current csv's there, but will work on creating raws to get out soon.

**Review by emapple — CHANGES_REQUESTED** [review]
This deletes the energy_usage.ipynb -- is that something we want to do? It also still has all the ipynb checkpoint files that we don't want to include.

Have you done this yet?
```
git checkout master
git pull
git checkout kyle_local
git merge master
```

It will come up with conflics that you'll have to fix.

Alternatively... at this point, the only thing that we want to add are the csv files, right? So maybe we should start clean. Checkout the master branch. Make a new branch called `add-csvs` or something like that. Then copy over the csvs, git add them, git commit them, and make a new pull request.

Sorry this is such a headache, our commit history got all screwy because we switched from private to public.

**Comment by kdettman** [comment]
I've removed all files that aren't the csv's. Does this mean now that they're no longer to be updated or that they will be removed entirely? If its the later then I'll just start clean.

**Comment by kdettman** [comment]
I will close this pull request and attempt this again with a different pull request.

**Pull request closed without merging**
